# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
DISABLE_LINTERS:
  - SPELL_PROSELINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: .eslintrc.js
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_FILTER_REGEX_EXCLUDE: .eslintrc.js
ENV_DOTENV_LINTER_FILE_EXTENSIONS: ['.env', '.env.example']
BASH_EXEC_FILTER_REGEX_INCLUDE: .husky
BASH_EXEC_FILE_EXTENSIONS: ['']
BASH_SHELLCHECK_ARGUMENTS: -e SC1091
BASH_SHELLCHECK_FILTER_REGEX_INCLUDE: .husky
BASH_SHELLCHECK_FILE_EXTENSIONS: ['']
BASH_SHFMT_FILTER_REGEX_INCLUDE: .husky
BASH_SHFMT_FILE_EXTENSIONS: ['']
REPOSITORY_TRIVY_DISABLE_ERRORS: true
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: LICENSE
